music/urls.py
from django.urls import path
from . import views

app_name = "music"

urlpatterns = [
    path("search/", views.search, name="search"),
    path('create/', views.create, name='create'),
]

unbreakable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.main, name='main'),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
    path('music/', include('music.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
# Create your models here.

class Song(models.Model):
    # song 제목
    song_title = models.CharField(max_length=100)
    # youtube 링크
    song_url = models.CharField(max_length=400)
    # 이미지 필드
    song_thumbnail = models.CharField(max_length=400)
    # 재생 시간
    song_runtime = models.CharField(max_length=10)

music/forms.py
from django import forms
from .models import Song

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = [
            'song_title',
            'song_url',
            'song_thumbnail',
            'song_runtime',
        ]
        labels = {
            'song_title' : '제목',
            'song_thumbnail' : '이미지',
            'song_url' : 'url',
            'song_runtime':'재생 시간',
        }

music/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# search
import requests
from django.conf import settings
from isodate import parse_duration
from .forms import SongForm
from .models import Song

# Create your views here.
# search view start
def search(request):
    videos = []

    if request.method == "POST":
        search_url = "https://www.googleapis.com/youtube/v3/search"
        video_url = "https://www.googleapis.com/youtube/v3/videos"

        search_params = {
            "part": "snippet",
            "q": request.POST["search"],
            "key": settings.YOUTUBE_DATA_API_KEY,
            "maxResults": 6,
            "type": "video",
        }

        r = requests.get(search_url, params=search_params)
        results = r.json()["items"]

        video_ids = []
        for result in results:
            video_ids.append(result["id"]["videoId"])

        # if request.POST["submit"] == "lucky":
        #     return redirect(f"https://www.youtube.com/watch?v={ video_ids[0] }")

        video_params = {
            "key": settings.YOUTUBE_DATA_API_KEY,
            "part": "snippet,contentDetails",
            "id": ",".join(video_ids),
            "maxResults": 6,
        }

        r = requests.get(video_url, params=video_params)

        results = r.json()["items"]

        for result in results:
            video_data = {
                "title": result["snippet"]["title"],
                "id": result["id"],
                "url": f'https://www.youtube.com/watch?v={ result["id"] }',
                "duration": 
                    parse_duration(result["contentDetails"]["duration"])
                ,
                "thumbnail": result["snippet"]["thumbnails"]["high"]["url"],
                "info":[result["snippet"]["title"],
                f'https://www.youtube.com/watch?v={ result["id"] }',
                result["snippet"]["thumbnails"]["high"]["url"],
                ]
            }

            videos.append(video_data)

    context = {
        "videos": videos,
    }
    # messages.success(request, "검색 결과입니다.")
    return render(request, "music/search.html", context)

# END Search
@login_required
def create(request):
    if request.method == 'POST':
        check = Song.objects.filter(song_url = request.POST['song_url'])
        if check:
            return HttpResponse('<script type="text/javascript">window.close()</script>')
        songform = SongForm(request.POST, request.FILES)
        if songform.is_valid():
            song = songform.save(commit=False)
            song.song_title = song.song_title.replace('\"', '\'')
            song.save()
    return HttpResponse('<script type="text/javascript">window.close()</script>')

music/templates/music/search.html
{% extends 'base-only.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="/static/music/css/search.css">
{% endblock css %}

{% block content %}
<div class="min">

  <section class="text-center">
    <div class="container">
      <div class="search-text-box">
        <h1 class="mb-5 search-text rounded-3">유튜브에서 음악 검색</h1>
      </div>
      <form method="POST">
        <div class="input-group mb-3">
          {% csrf_token %}
          <input type="text" name="search" placeholder="검색어에 따라 6개의 결과물을 출력해 줍니다." class="form-control input-box" aria-label="Username">
          <button type="submit" name="submit" value="search" class="btn px-5 btn-submit">검색</button>
        </div>
        <div class="fw-bold">(재생할 수 없는 영상은 글이나 메세지에 첨부하여도 재생이 안 되요)</div>
      </form>
    </div>
  </section>

  <div class="py-5">
    <div class="container">
      <div class="row">
        {% for video in videos %}
        <div class="col-6 col-md-4 mb-4">
          <form class="h-100" action="{% url 'music:create' %}" method="post">
            {% csrf_token %}
            <input name="song_title" style="display: none;" value='{{ video.title }}'></input>
            <input name="song_url" style="display: none;" value='{{ video.id }}'></input>
            <input name="song_thumbnail" style="display: none;" value='{{ video.thumbnail }}'></input>
            <input name="song_runtime" style="display: none;" value="{{ video.duration }}"></input>
          <div class="card shadow-sm h-100">
              <iframe class="youtube-player-4f3f462072931" type="text/html" width="100%" height="225" src="http://www.youtube.com/embed/{{ video.id }}" frameborder="0"></iframe>
            <div class="card-body card-box">
              <p class="card-text music-title">{{ video.title }}</p>
              <div class="d-flex justify-content-between align-items-center my-3 music-detail">
                <small class="text-muted">{{ video.duration }}</small>
                <button type="submit" class="btn btn-submit add-btn">노래 추가하기</button>
              </div>
            </div>
          </div>
        </form>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}