accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    # CRUD
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('<int:user_pk>/update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
    path('<int:user_pk>/profile/', views.profile, name="profile"),
    path('password/', views.password, name="password"),
    # 카카오 소셜 로그인
    path('kakao/login/callback/', views.kakao_callback, name="kakao_callback"),
    path('kakao/login/', views.kakao_request, name="kakao"),
    # 메시지(쪽지)
    path('<int:user_pk>/<int:articles_pk>/message_create/', views.message_create, name="message_create"),
    path('message_receive/', views.message_receive, name="message_receive"),
    path('message_delete/', views.message_delete, name="message_delete"),
    path('message_delete_all/', views.message_delete_all, name="message_delete_all"),
    path('<int:message_pk>/message_detail/', views.message_detail, name="message_detail"),
    # 메시지 신고
    path('<int:message_pk>/message_declaration', views.message_declaration, name="message_declaration"),
    path('feeling_page/', views.feeling_page, name="feeling_page"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("calendar", views.calendar, name="calendar"),
    path("", views.articles_index, name="articles_index"),
    path("articles_create/", views.articles_create, name="articles_create"),
    path("song_search/", views.song_search, name="song_search"),
    path(
        "<int:articles_pk>/articles_detail/",
        views.articles_detail,
        name="articles_detail",
    ),
    path(
        "<int:articles_pk>/articles_delete/",
        views.articles_delete,
        name="articles_delete",
    ),
    path(
        "<int:articles_pk>/articles_update/",
        views.articles_update,
        name="articles_update",
    ),
    path(
        "<int:articles_pk>/articles_detail/comments/",
        views.comment_create,
        name="comment_create",
    ),
    path(
        "<int:articles_pk>/articles_detail/comments/<int:comment_pk>/comment_delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path(
        "<int:articles_pk>/articles_declaration/",
        views.articles_declaration,
        name="articles_declaration",
    ),
    path(
        "<int:articles_pk>/<int:comment_pk>/comment_declaration",
        views.comment_declaration,
        name="comment_declaration",
    ),
    path("id-sort/", views.id_sort, name="id_sort"),
    path("calendar-detail/<str:date>/", views.calendar_detail, name="calendar_detail"),
    path('<int:articles_pk>/happy/', views.happy, name="happy"),
    path('<int:articles_pk>/sad/', views.sad, name="sad"),
    path('<int:articles_pk>/angry/', views.angry, name="angry"),
    path('<int:articles_pk>/funny/', views.funny, name="funny"),
]

music/urls.py
from django.urls import path
from . import views

app_name = "music"

urlpatterns = [
    path("search/", views.search, name="search"),
    path('create/', views.create, name='create'),
]

unbreakable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.main, name='main'),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
    path('music/', include('music.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from articles.models import Articles
from music.models import Song
import re
from django.forms import ValidationError

# Create your models here.

with open("badwords.txt", encoding="UTF8") as file:
    CENSORED_WORDS = file.read().splitlines()


def validate_text(text):
    words = set(re.sub("[^\w]", " ", text).split())
    for censored in words:
        if censored in CENSORED_WORDS:
            raise ValidationError(f"{censored}은(는) 쓰지 말아주세요!!")


class User(AbstractUser):
    birthday = models.DateField(
        null=True, blank=True
    )  # null=True 조건을 빼야하는데 소셜 로그인 이슈로 일단 추가
    phone_number = models.CharField(max_length=15)
    fullname = models.CharField(max_length=30)


class Message(models.Model):
    sender = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="re_sender"
    )
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    articles = models.ForeignKey(Articles, on_delete=models.CASCADE)
    content = models.CharField(max_length=100, validators=[validate_text])
    song = models.ForeignKey(Song, on_delete=models.SET_NULL, null=True)
    read = models.BooleanField(default=0)


class MessageDeclaration(models.Model):
    reporter = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="message_reporter",
    )
    reported = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="message_writer",
    )
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["reporter", "message"], name="only_one_report3"
            )
        ]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from .models import *

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["username","fullname","birthday","phone_number"]
        labels =  {
            'username':'ID',
            'fullname':'성함',
            'birthday':'생년월일',
            'phone_number':'전화번호',
        }

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ["fullname","birthday","phone_number"]
        labels = {
            'fullname':'성함',
            'birthday':'생년월일',
            'phone_number':'전화번호',
        }

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["content"]
        labels = {
            'content': '내용',
        }

class MessageDeclarationForm(forms.ModelForm):
    class Meta:
        model = MessageDeclaration
        fields = ['content']
        labels = {
            'content':'신고내용',
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from .forms import *
from django.views.decorators.http import require_POST
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import update_session_auth_hash
import requests
import json
from .models import *
from articles.models import *
from django.contrib import messages

# Create your views here.


def signup(request):
    # 이미 회원가입한 유저라면
    # if request.user.is_authenticated:
    #     return redirect("accounts:index")

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect(request.GET.get("next") or "main")
        else:
            form = CustomUserCreationForm()
            context = {
                "form": form,
                "validate": 1,
            }
            return render(request, "accounts/signup.html", context)
    else:
        form = CustomUserCreationForm()
        context = {
            "form": form,
            "validate": 0,
        }
        return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request.POST, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            message_d = MessageDeclaration.objects.filter(reported=request.user.pk)
            comment_d = CommentDeclaration.objects.filter(reported=request.user.pk)
            articles_d = ArticlesDeclaration.objects.filter(reported=request.user.pk)
            if len(message_d) + len(comment_d) + len(articles_d) >= 3:
                # 임시
                auth_logout(request)
                messages.warning(request, "정지된 계정입니다. 운영자에게 문의해주세요.")
                return redirect("main")
            else:
                return redirect(request.GET.get("next") or "main")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect("main")


@login_required
def update(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)
    if user == request.user:
        if request.method == "POST":
            form = CustomUserChangeForm(request.POST, instance=user)
            if form.is_valid():
                form.save()
                return redirect("accounts:profile", user_pk)
        else:
            form = CustomUserChangeForm(instance=user)
        context = {
            "form": form,
        }
        return render(request, "accounts/update.html", context)
    else:
        return render(request, "main.html")


@login_required
def profile(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)
    articles = user.articles_set.filter(user=user.pk)
    message = Message.objects.filter(receiver_id=user.pk).order_by("-articles")
    feelings = Sympathy.objects.filter(user=user_pk)
    liked = []
    for article in feelings:
        for i in liked:
            if article.articles == i.articles:
                break
        else:
            liked.append(article)
    context = {
        "user": user,
        "articles": articles,
        "message": message,
        "feelings": len(liked),
    }
    return render(request, "accounts/profile.html", context)


@login_required
def message_receive(request):
    message = Message.objects.filter(receiver_id=request.user).order_by("-pk")

    if message:
        context = {
            "message": message,
            "message_declaration_form": MessageDeclarationForm(),
        }
    else:
        context = {
            "message": 1,
        }

    return render(request, "accounts/message_receive.html", context)


@login_required
def delete(request):
    user = get_user_model().objects.get(pk=request.user.pk)
    user.delete()
    return redirect("main")


# 비밀번호 변경
@login_required
def password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            # 로그인 유지
            update_session_auth_hash(request, request.user.pk)
            return redirect("accounts:profile", request.user.pk)
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/password.html", context)


# 카카오 소셜 로그인
def kakao_request(reqeust):
    kakao_api = "https://kauth.kakao.com/oauth/authorize?response_type=code"
    redirect_uri = "http://unbreakableheart-env.eba-fq3y3emz.ap-northeast-2.elasticbeanstalk.com/accounts/kakao/login/callback/"
    client_id = "fdc7989db5f7e970c9ba50edb78ec9a6"
    return redirect(f"{kakao_api}&client_id={client_id}&redirect_uri={redirect_uri}")


def kakao_callback(request):
    data = {
        "grant_type": "authorization_code",
        "client_id": "fdc7989db5f7e970c9ba50edb78ec9a6",
        "redirect_uri": "http://unbreakableheart-env.eba-fq3y3emz.ap-northeast-2.elasticbeanstalk.com/accounts/kakao/login/callback/",
        "code": request.GET.get("code"),
    }

    kakao_token_api = "https://kauth.kakao.com/oauth/token"
    access_token = requests.post(kakao_token_api, data=data).json()["access_token"]

    headers = {"Authorization": f"bearer ${access_token}"}
    kakao_user_api = "https://kapi.kakao.com/v2/user/me"
    kakao_user_information = requests.get(kakao_user_api, headers=headers).json()
    kakao_id = kakao_user_information["id"]
    kakao_nickname = kakao_user_information["properties"]["nickname"]
    kakao_birthday = kakao_user_information["kakao_account"].get("birthday")

    # 받아온 kakao 유저정보중 id가 db에 있는지 확인합니다.
    if get_user_model().objects.filter(username=kakao_id).exists():
        kakao_user = get_user_model().objects.get(username=kakao_id)
        # kakao_user.refresh_token = temp["refresh_token"]
        kakao_user.save()
    else:
        kakao_login_user = get_user_model().objects.create(
            username=kakao_id,
            fullname=kakao_nickname,
            birthday=kakao_birthday,
            # refresh_token = temp["refresh_token"],
        )
        kakao_login_user.save()
        kakao_user = get_user_model().objects.get(username=kakao_id)
    auth_login(request, kakao_user, backend="django.contrib.auth.backends.ModelBackend")
    return redirect(request.GET.get("next") or "main")


@login_required
def message_create(request, user_pk, articles_pk):
    articles = Articles.objects.get(pk=articles_pk)
    receiver = User.objects.get(pk=user_pk)
    if request.method == "POST":
        message_form = MessageForm(request.POST)
        if message_form.is_valid:
            message = message_form.save(commit=False)
            message.sender = request.user
            message.receiver = receiver
            message.articles = articles
            if request.POST["song"]:
                song = Song.objects.get(song_title=request.POST["song"])
                message.song = song
            message.save()
            return redirect("articles:articles_detail", articles_pk)
    else:
        message_form = MessageForm()
    context = {
        "receiver": receiver,
        "message_form": message_form,
    }
    return render(request, "accounts/message_create.html", context)


@login_required
def message_delete(request):
    message = Message.objects.filter(receiver_id=request.user).order_by("-articles")
    if request.method == "POST":

        selected = request.POST.getlist("selected")
        print(selected)
        for m in message:
            for s in selected:
                if m.id == int(s):
                    m.delete()
    return redirect("accounts:message_receive")


@login_required
def message_delete_all(request):
    message = Message.objects.filter(receiver_id=request.user)
    message.delete()
    return redirect("accounts:message_receive")


def message_detail(request, message_pk):
    message = Message.objects.get(pk=message_pk)
    message.read = True
    message.save()
    context = {
        "message": message,
        "message_declaration_form": MessageDeclarationForm(),
    }
    return render(request, "accounts/message_detail.html", context)


# 메시지 신고
from django.db import IntegrityError


@login_required
def message_declaration(request, message_pk):
    message = Message.objects.get(pk=message_pk)
    if request.method == "POST":
        message_declaration_form = MessageDeclarationForm(request.POST)
        if message_declaration_form.is_valid():
            try:
                declaration = message_declaration_form.save(commit=False)
                declaration.reporter = request.user
                declaration.reported = message.sender
                declaration.message = message
                message_declaration_form.save()
                messages.warning(request, "신고되었습니다.")
                return redirect("accounts:message_detail", message_pk)
            except IntegrityError:
                messages.info(request, "이미 신고된 메시지입니다.")
                return redirect("accounts:message_detail", message_pk)
    else:
        message_declaration_form = MessageDeclarationForm()
    context = {
        "message_declaration_form": message_declaration_form,
    }
    return render(request, "accounts/message_receive.html", context)


def counter(request):
    count = 0
    try:
        if request.user.is_authenticated:
            message = Message.objects.filter(receiver=request.user)
            for m in message:
                if m.read == 0:
                    count += 1
        else:
            pass
    except Message.DoesNotExist:

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block css %}
<!-- <link rel="stylesheet" href="/static/css/accounts.css"> -->
<link rel="stylesheet" href="/static/accounts/css/login.css">
{% endblock css %}
{% block content %}

<!-- login -->

<div class="text-center login-box">
    <h1 class="text1">로그인</h1>

    <form class="form-signin form1" action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        <div class="input-text">
            <input class="input-box input-id width" type="text" name="username" id="id" class="form-control" placeholder="아이디" required autofocus readonly onfocus="this.removeAttribute('readonly');">
        </div>
        <div class="input-text">
            <input class="input-box input-password width" type="password" name="password" id="pw" class="form-control" placeholder="비밀번호" required autofocus readonly onfocus="this.removeAttribute('readonly');">
        </div>
        <button class="btn login-btn width" type="submit">로그인</button>
    </form>
    <a href="{% url 'accounts:kakao' %}"><button class="btn kakao-btn width">카카오 로그인</button></a><br>
    <div class="pt-3">
        <a align="center" class="signup-link" href="{% url 'accounts:signup' %}">회원가입 하러가기</a>
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/message_create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<!-- <link rel="stylesheet" href="/static/css/btn.css">
<link rel="stylesheet" href="/static/css/search2.css"> -->
<link rel="stylesheet" href="/static/accounts/css/message_create.css">
{% endblock css %}

{% block content %}
<div class="d-flex justify-content-center">
  <div class="card m-5 p-5 main_style">

    <h1>메시지 작성</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form message_form %}
      <input id="search_input" class="reviewcreate-userinfo" name="song" type="search" placeholder="클릭 후 노래를 검색하세요"
        aria-label="Search" autocomplete="off">
      <div>원하는 노래가 없다면
        <a class="text-decoration-none" href="{% url 'music:search' %}"
          onclick="window.open(this.href, '_blank', 'width=800, height=600, toolbars=no, scrollbars=yes'); return false;">노래
          추가</a>
        <div class="search-off search-div " id="search_box"></div>

      </div>
      <input class="btn-two purple mt-3" type="submit" value="메세지 보내기">
    </form>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'accounts/js/message_create.js' %}"></script>
{% endblock content %}

accounts/templates/accounts/message_receive.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block css %}
<!-- <link rel="stylesheet" href="/static/css/message_receive.css">
<link rel="stylesheet" href="/static/css/btn.css"> -->
<link rel="stylesheet" href="/static/accounts/css/message_receive.css">
{% endblock css %}

{% block content %}

<h4 class="text-center text-white mt-5">내가 받은 메시지</h4>
{% if message == 1 %}
<p class="text-center text-white mt-4">받은 메시지가 없습니다.</p>
{% else %}
<div class="message_receive_3 mt-4"></div>
<!-- 메시지 전체 삭제 Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">전체 삭제</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>전체 삭제하시겠습니까?</p>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <a href="{% url 'accounts:message_delete_all' %}" type="submit" class="btn btn-danger">삭제하기</a>
                </div>
            </div>
        </div>
    </div>
</div>

<form class="" action="{% url 'accounts:message_delete' %}" method="POST">
    {% csrf_token %}
    <div class="message_receive_3">
        <button class="btn d-flex part" type="submit">선택 삭제</button>
        <button class="btn ms-2 fw-bold whole" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">전체 삭제</button>
    </div>

    <div style="height:1rem;"></div>
    <!-- 메세지들 -->
    {% for m in message %}
    <div class="d-flex justify-content-center py-2 mb-2">
        <div class="second py-2 px-2">
            <input type="checkbox" style="width:1rem; height:1rem; margin-left:1rem;" id="selected" name="selected" value="{{m.id}}">
            <span>{{ m.articles.created_at |date:'Y-m-d' }}에 작성한 일기로부터</span>
            <hr style="margin-top:0;">
            <a class="text-decoration-none" href="{% url 'accounts:message_detail' m.pk %}" style="color:black;"><p class="ms-3 message_receive_1 short">{{ m.content }}</p></a>
        </div>
    </div>
    {% endfor %}

</form>
{% endif %}
<div class="container base_6"></div>
{% endblock content %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block css %}
<!-- <link rel="stylesheet" href="/static/css/btn.css"> -->
<link rel="stylesheet" href="/static/accounts/css/password.css">
{% endblock css %}
{% block content %}
<div class="container main_style">
    <div class=" p-5">
        <h1 class="mx-5">비밀번호 변경</h1>
        <form class="mx-5 mb-5" action="{% url 'accounts:password' %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input class="btn-two purple" type="submit" value="확인">
        </form>
    </div>
</div>
<div class="container base_6"></div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block css %}
<link rel="stylesheet" href="/static/accounts/css/profile.css">
{% endblock css %}

{% block content %}
<div class="container">
	<div class="front side">
		<div class="content">
			<h1>마이페이지</h1>
            <p class="mt-2 p1 fs-4">새벽 세 시 - 홍해리</p>
            <p class="fs-5">단단한 어둠이 밤을 내리찍고 있다</p>
            <p class="fs-5">허공에 걸려 있는</p>
            <p class="fs-5">칠흑의 도끼</p>
            <p class="fs-5">밤은 비명을 치며 깨어지고</p>
            <p class="fs-5">빛나는 적막이 눈을 말똥처럼 뜨고 있다</p>
		</div>
	</div>
	<div class="back side">
		<div class="content">
			<h1>{{ user.fullname }}님의 개인정보</h1>
            <div class="mt-5">
                <p class="fs-4 p2"><b>아이디</b> : {{ user.username }}</p>
                <p class="fs-4 p2"><b>전화번호</b> : {{ user.phone_number }}</p>
                <p class="fs-4 p2"><b>생일</b> : {{ user.birthday }}</p>
            </div>
            <div class="d-flex flex-row justify-content-center">
                <div class="d-flex flex-column align-items-center mx-3"><p class="text1">나의 일기</p><h6 ><a class="text-decoration-none" style="color: rgb(255, 255, 255);" href="{% url 'main' %}">{{ articles.count }}개</a></h6></div>
                <div class="d-flex flex-column align-items-center mx-3"><p class="text1">받은 메세지</p><h6><a class="text-decoration-none" style="color: rgb(255, 255, 255);" href="{% url 'accounts:message_receive' %}">{{ message.count }}개</a></h6></div>
                <div class="d-flex flex-column align-items-center mx-3"><p class="text1">공감한 글</p><h6><a class="text-decoration-none" style="color: rgb(255, 255, 255);" href="{% url 'accounts:feeling_page' %}">{{feelings}}개</a></h6></div>
            </div>
            <div class="d-flex justify-content-end">
                <a class="btn-two purple t1" href="{% url 'accounts:update' user.pk %}">수정</a>
                <a class="btn-two purple mx-2 t1" href="" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">탈퇴</a>
                <a class="btn-two purple t1" href="{% url 'accounts:password' %}">비밀번호 변경</a>
            </div>
		</div>
	</div>
    <!-- 탈퇴 Modal -->
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">탈퇴하기</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>정말로 탈퇴하시겠습니까?</p>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <a href="{% url 'accounts:delete' %}" type="submit" class="btn btn-danger">탈퇴하기</a>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<!-- <link rel="stylesheet" href="/static/css/btn.css"> -->
<link rel="stylesheet" href="/static/accounts/css/update.css">
{% endblock css %}

{% block content %}
<div class="container main_style">
  <div class="p-5">
    <h1 class="mx-5">회원 수정</h1>
    <form class="mx-5 mb-5" action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input class="btn-two purple" type="submit" value="확인">
    </form>
  </div>
</div>
<div class="container base_6"></div>
{% endblock content %}