accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    # CRUD
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('<int:user_pk>/update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
    path('<int:user_pk>/profile/', views.profile, name="profile"),
    path('password/', views.password, name="password"),
    # 카카오 소셜 로그인
    path('kakao/login/callback/', views.kakao_callback, name="kakao_callback"),
    path('kakao/login/', views.kakao_request, name="kakao"),
    # 메시지(쪽지)
    path('<int:user_pk>/<int:articles_pk>/message_create/', views.message_create, name="message_create"),
    path('message_receive/', views.message_receive, name="message_receive"),
    path('message_delete/', views.message_delete, name="message_delete"),
    path('message_delete_all/', views.message_delete_all, name="message_delete_all"),
    path('<int:message_pk>/message_detail/', views.message_detail, name="message_detail"),
    # 메시지 신고
    path('<int:message_pk>/message_declaration', views.message_declaration, name="message_declaration"),
    path('feeling_page/', views.feeling_page, name="feeling_page"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("calendar", views.calendar, name="calendar"),
    path("", views.articles_index, name="articles_index"),
    path("articles_create/", views.articles_create, name="articles_create"),
    path("song_search/", views.song_search, name="song_search"),
    path(
        "<int:articles_pk>/articles_detail/",
        views.articles_detail,
        name="articles_detail",
    ),
    path(
        "<int:articles_pk>/articles_delete/",
        views.articles_delete,
        name="articles_delete",
    ),
    path(
        "<int:articles_pk>/articles_update/",
        views.articles_update,
        name="articles_update",
    ),
    path(
        "<int:articles_pk>/articles_detail/comments/",
        views.comment_create,
        name="comment_create",
    ),
    path(
        "<int:articles_pk>/articles_detail/comments/<int:comment_pk>/comment_delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path(
        "<int:articles_pk>/articles_declaration/",
        views.articles_declaration,
        name="articles_declaration",
    ),
    path(
        "<int:articles_pk>/<int:comment_pk>/comment_declaration",
        views.comment_declaration,
        name="comment_declaration",
    ),
    path("id-sort/", views.id_sort, name="id_sort"),
    path("calendar-detail/<str:date>/", views.calendar_detail, name="calendar_detail"),
    path('<int:articles_pk>/happy/', views.happy, name="happy"),
    path('<int:articles_pk>/sad/', views.sad, name="sad"),
    path('<int:articles_pk>/angry/', views.angry, name="angry"),
    path('<int:articles_pk>/funny/', views.funny, name="funny"),
]

music/urls.py
from django.urls import path
from . import views

app_name = "music"

urlpatterns = [
    path("search/", views.search, name="search"),
    path('create/', views.create, name='create'),
]

unbreakable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.main, name='main'),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
    path('music/', include('music.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/forms.py
from django import forms
from .models import *
from django.forms import FileInput, Select


class ArticlesForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = [
            "music_start",
            "content",
            "feelings",
            "picture",
            "disclosure",
        ]
        labels = {
            "content": "오늘의 하루",
            "picture": "이미지",
            "feelings": "감정표현",
            "music_start": "음악을 재생할 위치를 정해주세요.(초)",
            "disclosure": "공개하기",
        }
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "class": "border border-dark rounded-15 mx-1",
                    "style": "background: transparent; border-radius:15px; border:1.5px solid rgb(51, 51, 51)!important; box-shadow:none!important;",
                    "placeholder": "당신의 오늘을 이야기해주세요.",
                }
            ),
            "picture": FileInput(
                attrs={
                    "class": "border border-dark rounded-15 mx-1",
                    "style": "background: transparent; border:1.5px solid rgb(51, 51, 51)!important; box-shadow:none!important;",
                }
            ),
            "feelings": Select(
                attrs={
                    "class": "border border-dark rounded-15 mx-1",
                    "style": "background: transparent; border:1.5px solid rgb(51, 51, 51)!important; box-shadow:none!important;",
                    "placeholder": "오늘의 기분을 말해주세요.",
                }
            ),
            "music_start": forms.NumberInput(
                attrs={
                    "class": "border border-dark rounded-15 mx-1",
                    "style": "background: transparent;border:1.5px solid rgb(51, 51, 51)!important; box-shadow:none!important;",
                }
            ),
            "disclosure": forms.CheckboxInput(
                attrs={"class": "form-check-input", "id": "flexSwitchCheckChecked"}
            ),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]

        widgets = {
            "content": forms.Textarea(
                attrs={
                    "rows": 2,
                    "style": "background: transparent;",
                    "class": "border border-2 border-dark bg-white rounded-1 text-dark p-3 font-space shadow-sm scroll-none",
                }
            ),
        }

        labels = {
            "content": "",
        }


class ArticlesDeclarationForm(forms.ModelForm):
    class Meta:
        model = ArticlesDeclaration
        fields = [
            "content",
        ]
        labels = {
            "content": "신고내용",
        }


class CommentDeclarationForm(forms.ModelForm):
    class Meta:
        model = CommentDeclaration
        fields = [
            "content",
        ]
        labels = {
            "content": "신고내용",
        }

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import (
    ArticlesForm,
    CommentForm,
    ArticlesDeclarationForm,
    CommentDeclarationForm,
)
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
from accounts.models import Message
from .models import Articles, Sympathy, Comment
from django.utils import timezone
from music.models import Song
from django.views.generic.base import TemplateView
import json
from django.db.models import Q
import requests
from django.conf import settings

from django.contrib.auth.decorators import login_required
from django.db.models import Value
from django.db.models.functions import Replace


def calendar(request):
    return render(request, "articles/calendar.html")


def articles_index(request):
    articles = Articles.objects.filter(disclosure=True).order_by("-created_at")
    context = {
        "articles": articles,
    }
    return render(request, "articles/articles_index.html", context)


@login_required
def articles_create(request):
    if request.method == "POST":
        articles_form = ArticlesForm(request.POST, request.FILES)
        if articles_form.is_valid():
            articles = articles_form.save(commit=False)
            so = Song.objects.filter(song_title=request.POST["song"]).exists()
            if so:
                song = Song.objects.get(song_title=request.POST["song"])
                articles.song = song
            articles.user = request.user
            articles.save()
            return redirect("main")
    else:
        articles_form = ArticlesForm()
    context = {
        "articles_form": articles_form,
    }
    return render(request, "articles/articles_create.html", context)


def song_search(request):
    search_data = request.GET.get("search", "")
    song = Song.objects.filter(song_title__icontains=search_data).all()
    song_list = []
    for s in song:
        song_list.append(
            {
                "name": s.song_title,
                "url": s.song_url,
                "thumbnail": s.song_thumbnail,
                "id": s.pk,
            }
        )
    context = {
        "song_list": song_list,
    }
    return JsonResponse(context)


def articles_detail(request, articles_pk):
    articles = get_object_or_404(Articles, pk=articles_pk)
    if request.user.is_authenticated:
        happy = Sympathy.objects.filter(articles=articles, user=request.user, feeling=1)
        sad = Sympathy.objects.filter(articles=articles, user=request.user, feeling=2)
        angry = Sympathy.objects.filter(articles=articles, user=request.user, feeling=3)
        funny = Sympathy.objects.filter(articles=articles, user=request.user, feeling=4)
    else:
        happy = 0
        sad = 0
        angry = 0
        funny = 0
    
    context = {
        "articles": articles,
        "comment_form": CommentForm(),
        "comments": articles.comment_set.all(),
        "articles_declaration_form": ArticlesDeclarationForm(),
        "comment_declaration_form": CommentDeclarationForm(),
        'f1':happy,
        'f2':sad,
        'f3':angry,
        'f4':funny,
    }
    return render(request, "articles/articles_detail.html", context)


@login_required
def articles_delete(request, articles_pk):
    articles = get_object_or_404(Articles, pk=articles_pk)
    if request.user == articles.user:
        articles.delete()
        return redirect("articles:articles_index")  # 아마도 메인페이지?
    return redirect("articles:articles_detail", articles_pk)


@login_required
def articles_update(request, articles_pk):
    articles = get_object_or_404(Articles, pk=articles_pk)
    if request.user == articles.user:
        if request.method == "POST":
            articles_form = ArticlesForm(request.POST, request.FILES, instance=articles)
            if articles_form.is_valid():
                article = articles_form.save(commit=False)
                if request.POST["song"]:
                    so = Song.objects.get(song_title=request.POST["song"])
                    articles.song = so
                article.save()

            return redirect("articles:articles_detail", articles_pk)
        else:
            articles_form = ArticlesForm(instance=articles)
        context = {
            "articles_form": articles_form,
        }
        return render(request, "articles/articles_update.html", context)
    else:
        messages.warning(request, "작성자만 수정 할 수 있습니다.")
        return redirect("articles:articles_index")


@login_required
def comment_create(request, articles_pk):
    articles = get_object_or_404(Articles, pk=articles_pk)
    result = request.POST["parent"]

    if request.method == "POST":  # POST요청이고
        if request.user.is_authenticated:  # 로그인된 상태면
            # 댓글일 때
            if int(result) == 0:
                comment_form = CommentForm(request.POST)  # POST으로 요청온 정보를 받아서
                if comment_form.is_valid():  # 유효성 검사하고
                    comment = comment_form.save(commit=False)  # 저장 멈춰
                    # 외래키 입력
                    comment.articles = articles
                    comment.user = request.user
                    # 저장
                    comment.save()

                    context = {
                        "articles_pk": articles_pk,
                        "comment_pk": comment.pk,
                        "content": comment.content,
                        "userName": comment.user.username,
                    }
                    return JsonResponse(context)

            elif int(result) > 0:
                comment_form = CommentForm(request.POST)  # POST으로 요청온 정보를 받아서
                if comment_form.is_valid():  # 유효성 검사하고
                    comment = comment_form.save(commit=False)  # 저장 멈춰
                    # 외래키 입력
                    comment.articles = articles
                    comment.user = request.user
                    comment.parent_id = result
                    # 저장
                    comment.save()

                    context = {
                        "articles_pk": articles_pk,
                        "comment_pk": comment.pk,
                        "content": comment.content,
                        "userName": comment.user.username,
                    }
                    return JsonResponse(context)
        else:
            return HttpResponse(status=403)
    else:
        return redirect("accounts:login")


@login_required
def comment_delete(request, articles_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.user:
        if request.method == "POST":
            comment.delete()

    data = {}
    return JsonResponse(data)

# 공감 표현
# 행복
@login_required
def happy(request, articles_pk):
    articles = Articles.objects.get(pk=articles_pk)
    sympathy = Sympathy.objects.filter(articles=articles, user=request.user, feeling=1)
    if sympathy:
        sympathy.delete()
        s = False
    else:
        Sympathy.objects.create(articles=articles, user=request.user, feeling=1)
        s = True
    data = {
        's': s,
    }
    return JsonResponse(data)
# 슬픔
def sad(request, articles_pk):
    articles = Articles.objects.get(pk=articles_pk)
    sympathy = Sympathy.objects.filter(articles=articles, user=request.user, feeling=2)
    if sympathy:
        sympathy.delete()
        s = False
    else:
        Sympathy.objects.create(articles=articles, user=request.user, feeling=2)
        s = True
    data = {
        's': s,
    }
    return JsonResponse(data)
# 화남
def angry(request, articles_pk):
    articles = Articles.objects.get(pk=articles_pk)
    sympathy = Sympathy.objects.filter(articles=articles, user=request.user, feeling=3)
    if sympathy:
        sympathy.delete()
        s = False
    else:
        Sympathy.objects.create(articles=articles, user=request.user, feeling=3)
        s = True
    data = {
        's': s,
    }
    return JsonResponse(data)
# 웃김
def funny(request, articles_pk):
    articles = Articles.objects.get(pk=articles_pk)
    sympathy = Sympathy.objects.filter(articles=articles, user=request.user, feeling=4)
    if sympathy:
        sympathy.delete()
        s = False
    else:
        Sympathy.objects.create(articles=articles, user=request.user, feeling=4)
        s = True
    data = {
        's': s,
    }
    return JsonResponse(data)


# 게시글 신고
from django.db import IntegrityError


@login_required
def articles_declaration(request, articles_pk):
    articles = Articles.objects.get(pk=articles_pk)
    if request.method == "POST":
        articles_declaration_form = ArticlesDeclarationForm(request.POST)
        if articles_declaration_form.is_valid():
            try:
                declaration = articles_declaration_form.save(commit=False)
                declaration.reporter = request.user
                declaration.reported = articles.user
                declaration.articles = articles
                articles_declaration_form.save()
                messages.warning(request, "신고되었습니다.")
                return redirect("articles:articles_detail", articles_pk)
            except IntegrityError:
                messages.info(request, '이미 신고한 게시글입니다.')
                return redirect("articles:articles_detail", articles_pk)
    else:
        articles_declaration_form = ArticlesDeclarationForm()
    context = {
        "articles_declaration_form": articles_declaration_form,
    }
    return render(request, "articles/articles_detail.html", context)


@login_required
def comment_declaration(request, articles_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == "POST":
        comment_declaration_form = CommentDeclarationForm(request.POST)
        if comment_declaration_form.is_valid():
            try:
                declaration = comment_declaration_form.save(commit=False)
                declaration.reporter = request.user
                declaration.reported = comment.user

articles/templates/articles/articles_create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<!-- <link rel="stylesheet" href="/static/css/search.css">
<link rel="stylesheet" href="/static/css/articles_create.css">
<link rel="stylesheet" href="/static/css/btn.css"> -->
<link rel="stylesheet" href="/static/articles/css/articles_create.css">
{% endblock css %}
{% block content %}
<div class="main_position" >
  <div class="main_style">
    <div> 
      <h3 class="main_title" align="center"><span class="title_name">{{ user.fullname }}</span>님의 오늘은 어떠신가요?</h3>
    </div>
    <div class="main_position ">
      <form class="main_search" action="" method="POST" enctype="multipart/form-data" >
        <div>
          <label>오늘의 음악</label>
        </div>
        <input id="search_input" class="reviewcreate-userinfo main_today_search" name="song" type="search "
          placeholder="당신의 하루를 나타내는 음악을 선택해주세요." aria-label="Search" autocomplete="off">
          <div>원하는 노래가 없다면
            <a class="text-decoration-none" href="{% url 'music:search' %}"
            onclick="window.open(this.href, '_blank', 'width=800, height=600, toolbars=no, scrollbars=yes'); return false;">노래
            추가</a>
            <div class="search-off search-div " id="search_box"></div>
        </div>
        <br>
        {% csrf_token %}
        {% bootstrap_form articles_form %}
        <div class="main_create_button " style="">
          <button class="wdt btn submit-btn" type="submit">오늘의 일기 만들기</button>
        </div>
    </div>
    </form>
    <form id="search_form" action="{% url 'articles:song_search' %}" class="d-flex hidden" role="search"></form>
  </div>

</div>
<div style="height:10rem;"></div>


<!-- 스크립트-->

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'articles/js/articles_create.js' %}"></script>

{% endblock content %}

articles/templates/articles/articles_create_2.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container" style="padding:5rem;">
  <h1 class="text-start fs-5 mb-4 fw-bold font-space">글 작성</h1>
  <form action="" method="POST" class="my-3 font-space fw-semibold" style="font-size: 15px;"
    enctype="multipart/form-data">
    {% csrf_token %}
    <div class="font-space">
      {% bootstrap_form articles_form %}
    </div>
    {% bootstrap_button button_type="submit" button_class="btn btn-dark text-white w-100 rounded-0" content="리뷰 작성" %}
  </form>
</div>

{% endblock content %}

articles/templates/articles/articles_index.html
{% extends 'base.html' %} {% load static %} 
{% load django_bootstrap5 %}

{% block css %}
<!-- <link rel="stylesheet" href="/static/css/articles_index.css"> -->
<!-- <link rel="stylesheet" href="/static/calendar/css/calendar.css"> -->
<!-- <link rel="stylesheet" href="/static/css/timeline.css"> -->
<link rel="stylesheet" href="/static/articles/css/articles_index.css">
{% endblock css %}

{% block content %}
<div class="title ">
    <h1 class="rounded-3 title_is_user">함께하는 이야기📖</h1>
</div>
{% if request.user.is_authenticated %}
{% else %}
    <div class="add-a">
        <a class="form-control addtxt btn btn-light fs-6" href="{% url 'accounts:login' %}">로그인하러 가기</a>
    </div>
{% endif %}

<div class="container">
    {% for article in articles %}
    <div class="d-flex justify-content-center">

        {% if article.song or article.picture %}

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 my-4 card-box" onclick="location.href='http://unbreakableheart-env.eba-fq3y3emz.ap-northeast-2.elasticbeanstalk.com/articles/' + {{article.pk}} + '/articles_detail/';">
            <div class="col-md-6 col-sm-12" style="padding:0 12px;">
                {% if article.song %}
                    {% if article.picture %}
                    <div class="song_and_picture">
                        <div class="d-flex mt-4 rounded song-box justify-content-center">
                            <div class="col-5 song-img-box" >
                                <img class="song-img" src="{{ article.song.song_thumbnail }}" alt="" style="width:10vw;">
                            </div>
                            <div class="col-7 d-flex song-title-box">
                                <p class="mt-3 song-title">{{ article.song.song_title }}</p>
                            </div>
                        </div>
                        <div class="mb-4" style="height:100%; width:100%;">
                            <a href="{% url 'articles:articles_detail' article.pk %}"><img class="hover rounded diary_pic" src="{{ article.picture.url }}" alt="{{ article.picture }}"></a>
                        </div>
                    </div>
                    {% else %}
                    <div class="song_no_picture">
                        <div class="d-flex mt-4 rounded song-box justify-content-center">
                            <div class="col-5 song-img-box" >
                                <img class="song-img" src="{{ article.song.song_thumbnail }}" alt="" style="width:10vw;">
                            </div>
                            <div class="col-7 d-flex song-title-box">
                                <p class="mt-3 song-title">{{ article.song.song_title }}</p>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                {% else %}
                    {% if article.picture %}
                        <a href="{% url 'articles:articles_detail' article.pk %}"><img class="hover rounded diary_pic" src="{{ article.picture.url }}" alt="{{ article.picture }}" style="margin:1.5rem 0;"></a>                    
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-md-6 col-sm-12" style="padding:1.5rem 12px;">
                {% if article.picture %}
                    {% if article.song %}
                    <div class="">
                        <h1 class="mb-2 content-text text-center">누군가의 이야기</h1>
                        <p class="text-end mb-1 created_at">{{ article.created_at }}</p>
                        <a class="text-decoration-none text-dark" href="{% url 'articles:articles_detail' article.pk %}"><p class="long diary_content">{{ article.content | linebreaksbr }}</p></a>
                    </div>
                    {% else %}
                    <div class="">
                        <h1 class="mb-2 content-text text-center">누군가의 이야기</h1>
                        <p class="text-end mb-1 created_at">{{ article.created_at }}</p>
                        <a class="text-decoration-none text-dark" href="{% url 'articles:articles_detail' article.pk %}"><p class="middle diary_content">{{ article.content | linebreaksbr }}</p></a>
                    </div>
                    {% endif %}
                {% else %}
                    {% if article.song %}
                    <div class="no-picture-box">
                        <h1 class="mb-2 content-text text-center">누군가의 이야기</h1>
                        <p class="text-end mb-1 created_at">{{ article.created_at }}</p>
                        <a class="text-decoration-none text-dark" href="{% url 'articles:articles_detail' article.pk %}"><p class="short diary_content">{{ article.content | linebreaksbr }}</p></a>
                    </div>
                    {% endif %}
                {% endif %}
            </div> 
        </div>


        {% else %}

        <div class="row card-box my-4 no_song_no_picture" onclick="location.href='http://unbreakableheart-env.eba-fq3y3emz.ap-northeast-2.elasticbeanstalk.com/articles/' + {{article.pk}} + '/articles_detail/';">
            <div class="">
                <h1 class="mb-2 content-text text-center">누군가의 이야기</h1>
                <p class="text-end mb-1 created_at">{{ article.created_at }}</p>
                <a class="text-decoration-none text-dark" href="{% url 'articles:articles_detail' article.pk %}"><p class="middle diary_content">{{ article.content | linebreaksbr }}</p></a>
            </div>
        </div>

        {% endif %}
    </div>
    {% endfor %}
</div>
<script>
    function timeForToday(value) {
    const today = new Date(); //현재 시간
    const timeValue = new Date(value); //글 작성시간

    const betweenTime = Math.floor((today.getTime() - timeValue.getTime()) / 1000 / 60);
    if (betweenTime < 1) return '방금전';
    if (betweenTime < 60) {
        return `${betweenTime}분전`;
    }

    const betweenTimeHour = Math.floor(betweenTime / 60);
    if (betweenTimeHour < 24) {
        return `${betweenTimeHour}시간전`;
    }

    const betweenTimeDay = Math.floor(betweenTime / 60 / 24);
    if (betweenTimeDay < 365) {
        return `${betweenTimeDay}일전`;
    }

    return `${Math.floor(betweenTimeDay / 365)}년전`;
}
</script>

<div style="height:10rem;"></div>

<script src="{% static 'accounts/js/.js' %}"></script>

{% endblock content %}

articles/templates/articles/articles_update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<!-- <link rel="stylesheet" href="/static/css/btn.css"> -->
<!-- <link rel="stylesheet" href="/static/css/search.css">
<link rel="stylesheet" href="/static/css/articles_create.css"> -->
<link rel="stylesheet" href="/static/articles/css/articles_update.css">
{% endblock css %}
{% block content %}
<div class="body">
  <div class="user">
    <div>
      <h3 class="user-text">
        <span class="user-name">{{ user.fullname }}</span>님의 오늘은 어떠신가요?</h3>

    </div>

    <div class="search-bar">
      <form action="" method="POST" enctype="multipart/form-data" class="search-box">
        <div>
          <label>오늘의 음악</label>
        </div>
        <input id="search_input" class="reviewcreate-userinfo search-input" name="song" type="search "
          placeholder="당신의 하루를 나타내는 음악을 선택해주세요." aria-label="Search" autocomplete="off">
          <div>원하는 노래가 없다면
            <a class="text-decoration-none" href="{% url 'music:search' %}"
            onclick="window.open(this.href, '_blank', 'width=800, height=600, toolbars=no, scrollbars=yes'); return false;">노래
            추가</a>
            <div class="search-off search-div " id="search_box"></div>
        </div>
        <br>
        {% csrf_token %}
        {% bootstrap_form articles_form %}
        <div class="submit-button">
          <button class="wdt btn submit-btn" type="submit">수정하기</button>
        </div>
    </div>
    </form>
    <form id="search_form" action="{% url 'articles:song_search' %}" class="d-flex hidden" role="search"></form>
  </div>

</div>
<div style="height:10rem;"></div>


<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'articles/js/articles_update.js'%}"></script>
{% endblock content %}

articles/templates/articles/search.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://www.youtube.com/iframe_api"></script>
  <title>Search YouTube</title>
  <!-- Bootstrap core CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="{% static 'search/album.css' %}" rel="stylesheet">
</head>

<body>

  <main role="main">

    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Search YouTube</h1>
        <p class="lead text-muted">Get the top nine results on YouTube for your query!</p>
        <form method="POST">
          <div class="input-group mb-3">
            {% csrf_token %}
            <input type="text" name="search" class="form-control" aria-label="Username">
          </div>
          <p>
            <button type="submit" name="submit" value="search" class="btn btn-primary my-2">YouTube Search</button>

          </p>
        </form>
      </div>
    </section>

    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">
          {% for video in videos %}
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ video.thumbnail }}"
                preserveAspectRatio="xMidYMid slice" focusable="false" role="img"
                aria-label="Placeholder: Thumbnail"></img>
              <div class="card-body">
                <p class="card-text">{{ video.title }}</p>
                <p>https://youtu.be/{{ video.id }}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a type="button" href="{{ video.url }}" class="btn btn-sm btn-outline-secondary">View</a>
                  </div>
                  <small class="text-muted">{{ video.duration }} mins</small>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>

  </main>

</body>

</html>