accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    # CRUD
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('<int:user_pk>/update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
    path('<int:user_pk>/profile/', views.profile, name="profile"),
    path('password/', views.password, name="password"),
    # 카카오 소셜 로그인
    path('kakao/login/callback/', views.kakao_callback, name="kakao_callback"),
    path('kakao/login/', views.kakao_request, name="kakao"),
    # 메시지(쪽지)
    path('<int:user_pk>/<int:articles_pk>/message_create/', views.message_create, name="message_create"),
    path('message_receive/', views.message_receive, name="message_receive"),
    path('message_delete/', views.message_delete, name="message_delete"),
    path('message_delete_all/', views.message_delete_all, name="message_delete_all"),
    path('<int:message_pk>/message_detail/', views.message_detail, name="message_detail"),
    # 메시지 신고
    path('<int:message_pk>/message_declaration', views.message_declaration, name="message_declaration"),
    path('feeling_page/', views.feeling_page, name="feeling_page"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("calendar", views.calendar, name="calendar"),
    path("", views.articles_index, name="articles_index"),
    path("articles_create/", views.articles_create, name="articles_create"),
    path("song_search/", views.song_search, name="song_search"),
    path(
        "<int:articles_pk>/articles_detail/",
        views.articles_detail,
        name="articles_detail",
    ),
    path(
        "<int:articles_pk>/articles_delete/",
        views.articles_delete,
        name="articles_delete",
    ),
    path(
        "<int:articles_pk>/articles_update/",
        views.articles_update,
        name="articles_update",
    ),
    path(
        "<int:articles_pk>/articles_detail/comments/",
        views.comment_create,
        name="comment_create",
    ),
    path(
        "<int:articles_pk>/articles_detail/comments/<int:comment_pk>/comment_delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path(
        "<int:articles_pk>/articles_declaration/",
        views.articles_declaration,
        name="articles_declaration",
    ),
    path(
        "<int:articles_pk>/<int:comment_pk>/comment_declaration",
        views.comment_declaration,
        name="comment_declaration",
    ),
    path("id-sort/", views.id_sort, name="id_sort"),
    path("calendar-detail/<str:date>/", views.calendar_detail, name="calendar_detail"),
    path('<int:articles_pk>/happy/', views.happy, name="happy"),
    path('<int:articles_pk>/sad/', views.sad, name="sad"),
    path('<int:articles_pk>/angry/', views.angry, name="angry"),
    path('<int:articles_pk>/funny/', views.funny, name="funny"),
]

music/urls.py
from django.urls import path
from . import views

app_name = "music"

urlpatterns = [
    path("search/", views.search, name="search"),
    path('create/', views.create, name='create'),
]

unbreakable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.main, name='main'),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
    path('music/', include('music.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base-only.html
{% load django_bootstrap5 %}
{% load static %} 
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/mainstyle.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dongle:wght@300;400;700&family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    {% block css %}
    {% endblock css %}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <style>
    body{
        font-family: 'Noto Sans KR', sans-serif;
        font-weight: lighter;
        z-index:-2;
    }
    .bg{
        background-size: 330px;
        background-image: url('/static/images/bg.png');
    }
    </style>
</head>

<body>

<!-- header -->
<div class="bg">
    <div class="header-text" style="padding:2vh 0; z-index:2;">
        <!-- blank -->
        <div style="width:30%; padding-left:5vh;"></div>
        <!-- logo -->
        <div>
            <a href="{% url 'main' %}"><img class="logo-img" src="{% static 'images/logo2.png' %}" alt="logo" style="height:100px; width:100px;"></a>
        </div>
        <!-- blank -->
        <div style="width:30%; padding-left:5vh;"></div>
    </div>
    {% block content %}
    {% endblock content %}
</div>
<div class="container" style="height: 100px;"></div>


</body>

</html>

templates/base.html
{% load django_bootstrap5 %}
{% load static %} 
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="/static/images/favicon.png">
  <title>지금, 우린</title>
  <!-- CSS only -->
  <link rel="stylesheet" href="/static/css/style.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
  <link rel="stylesheet" href="/static/css/mainstyle.css">
  <link rel="stylesheet" href="/static/css/base.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Dongle:wght@300;400;700&family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
  <!-- profile font -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR&display=swap" rel="stylesheet">
  {% block css %}
  {% endblock css %}
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>

<body class="">

<!-- header -->
<div class="bg">
  <div class="bg">
    <div class="header-text base_1">
      <!-- blank -->
      <div class="base_2"></div>
      <!-- logo -->
      <div>
        <a href="{% url 'main' %}"><img class="logo-img base_3" src="{% static 'images/logo2.png' %}" alt="logo"></a>
      </div>
      <!-- login/bell -->
      <div class="top_account base_4">
        {% if request.user.is_authenticated %}
        <a class="top_account_img logo-bg" href="{% url 'accounts:logout' %}"><img src="{% static 'images/logout.png' %}" alt="logo" class="base_5"></a>
        <a class="top_account_img mx-3 logo-bg" href="{% url 'accounts:message_receive' %}"><img src="{% static 'images/bell.png' %}" alt="bell" class="base_5"></a>
        <div class="position-relative">
          <span class="cnt start-100 translate-middle badge rounded-pill bg-danger">{{count}}</span>
        </div>
        {% else %}
        <a class="top_account_img logo-bg" href="{% url 'accounts:login' %}"><img src="{% static 'images/login.png' %}" alt="logo" class="base_5"></a>
        <a class="top_account_img mx-3 logo-bg" href="{% url 'accounts:signup' %}"><img src="{% static 'images/signup.png' %}" alt="logo" class="base_5"></a>
        {% endif %}
      </div>
    </div>
    {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{message.tags}}" role="alert">
          {{message.message}}
      </div>
    {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}
  </div>
    <!-- nav bar -->
    <div class="nav-bar fixed-bottom">
      <a href="{% url 'articles:calendar' %}"><img class="nav-img base_7" src="{% static 'images/calendar2.png' %}" alt=""></a>
      <a href="{% url 'articles:articles_create' %}"><img class="nav-img base_8" src="{% static 'images/diary2.png' %}" alt=""></a>
      <a href="{% url 'articles:articles_index' %}"><img class="nav-img base_9" src="{% static 'images/community2.png' %}" alt="" ></a>
      {% if user.is_authenticated %}
      <a href="{% url 'accounts:profile' user.pk %}"><img class="nav-img base_5" src="{% static 'images/user2.png' %}" alt=""></a>
      {% else %}
      <a href="{% url 'accounts:login' %}"><img class="nav-img base_5" src="{% static 'images/user2.png' %}" alt=""></a>
      {% endif %}
    </div>
</div>

</body>

</html>

templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="/static/css/timeline.css">
    <link rel="stylesheet" href="/static/calendar/css/calendar.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
{% endblock css %}

{% block content %}
{% if request.user.is_authenticated %}
<div class="title">
    <h1 class="title_is_user rounded-3">나의 이야기📖</h1>
</div>
{% endif %}
{% if request.user.is_authenticated %}
    {% if not articles %}
        <div class="d-flex justify-content-center pt-3 pb-2">
            <a class="form-control addtxt btn btn-light fs-6" href="{% url 'articles:articles_create' %}">오늘의 일기 쓰러가기</a>
        </div>
    {% else %}
        <div class="d-flex justify-content-center pt-3 pb-2">
            <a class="form-control addtxt btn btn-light fs-6" href="{% url 'articles:articles_create' %}">오늘의 일기 쓰러가기</a>
        </div>
    {% endif %}
{% else %}
    <div style="height: 500px;" class="d-flex flex-column justify-content-center align-items-center mt-5">
        <p class="animated fadeInUp text-light fs-3 mb-3" style="animation-delay: 0s;">자신의 하루를 음악으로 기록하고 공유해주세요.</p>
        <p class="animated fadeInUp text-light fs-3 mb-3" style="animation-delay: 1.5s">누군가의 하루를 공감해주세요.</p>
        <p class="animated fadeInUp text-light fs-3 mb-3" style="animation-delay: 3s">여러분의 하루들로 페이지를 채워주세요.</p>
        <div class="d-flex justify-content-center pt-3 pb-2 animated fadeInUp mb-3" style="animation-delay: 4s">
            <a class="form-control addtxt btn btn-light fs-6" href="{% url 'accounts:login' %}">로그인하러 가기</a>
        </div>
    </div>
{% endif %}

<div class="container">
    {% for article in articles %}
    <div class="d-flex justify-content-center">

        {% if article.song or article.picture %}

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 my-4 card-box" onclick="location.href='http://unbreakableheart-env.eba-fq3y3emz.ap-northeast-2.elasticbeanstalk.com/articles/' + {{article.pk}} + '/articles_detail/';">
            <div class="col-md-6 col-sm-12" style="padding:0 12px;">
                {% if article.song %}
                    {% if article.picture %}
                    <div class="song_and_picture">
                        <div class="d-flex mt-4 rounded song-box justify-content-center">
                            <div class="col-5 song-img-box" >
                                <img class="song-img" src="{{ article.song.song_thumbnail }}" alt="" style="width:10vw;">
                            </div>
                            <div class="col-7 d-flex song-title-box">
                                <p class="mt-3 song-title">{{ article.song.song_title }}</p>
                            </div>
                        </div>
                        <div class="mb-4" style="height:100%; width:100%;">
                            <a href="{% url 'articles:articles_detail' article.pk %}"><img class="hover rounded diary_pic" src="{{ article.picture.url }}" alt="{{ article.picture }}"></a>
                        </div>
                    </div>
                    {% else %}
                    <div class="song_no_picture">
                        <div class="d-flex mt-4 rounded song-box justify-content-center">
                            <div class="col-5 song-img-box" >
                                <img class="song-img" src="{{ article.song.song_thumbnail }}" alt="" style="width:10vw;">
                            </div>
                            <div class="col-7 d-flex song-title-box">
                                <p class="mt-3 song-title">{{ article.song.song_title }}</p>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                {% else %}
                    {% if article.picture %}
                        <a href="{% url 'articles:articles_detail' article.pk %}"><img class="hover rounded diary_pic" src="{{ article.picture.url }}" alt="{{ article.picture }}" style="margin:1.5rem 0;"></a>                    
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-md-6 col-sm-12" style="padding:1.5rem 12px;">
                {% if article.picture %}
                    {% if article.song %}
                    <div class="picture-box">
                        <h1 class="mb-2 content-text text-center">나의 추억</h1>
                        <p class="text-end mb-1 created_at">{{ article.created_at }}</p>
                        <a class="text-decoration-none text-dark" href="{% url 'articles:articles_detail' article.pk %}"><p class="long diary_content">{{ article.content | linebreaksbr }}</p></a>
                    </div>
                    {% else %}
                    <div class="picture-box">
                        <h1 class="mb-2 content-text text-center">나의 추억</h1>
                        <p class="text-end mb-1 created_at">{{ article.created_at }}</p>
                        <a class="text-decoration-none text-dark" href="{% url 'articles:articles_detail' article.pk %}"><p class="middle diary_content">{{ article.content | linebreaksbr }}</p></a>
                    </div>
                    {% endif %}
                {% else %}
                    {% if article.song %}
                    <div class="no-picture-box">
                        <h1 class="mb-2 content-text text-center">나의 추억</h1>
                        <p class="text-end mb-1 created_at">{{ article.created_at }}</p>
                        <a class="text-decoration-none text-dark" href="{% url 'articles:articles_detail' article.pk %}"><p class="short diary_content">{{ article.content | linebreaksbr }}</p></a>
                    </div>
                    {% endif %}
                {% endif %}
            </div> 
        </div>


        {% else %}

        <div class="row card-box my-4 no_song_no_picture" onclick="location.href='http://unbreakableheart-env.eba-fq3y3emz.ap-northeast-2.elasticbeanstalk.com/articles/' + {{article.pk}} + '/articles_detail/';">
            <div class="picture-box">
                <h1 class="mb-2 content-text text-center">나의 추억</h1>
                <p class="text-end mb-1 created_at">{{ article.created_at }}</p>
                <a class="text-decoration-none text-dark" href="{% url 'articles:articles_detail' article.pk %}"><p class="middle diary_content">{{ article.content | linebreaksbr }}</p></a>
            </div>
        </div>

        {% endif %}
    </div>
    {% endfor %}
</div>
<script>
    function timeForToday(value) {
    const today = new Date(); //현재 시간
    const timeValue = new Date(value); //글 작성시간

    const betweenTime = Math.floor((today.getTime() - timeValue.getTime()) / 1000 / 60);
    if (betweenTime < 1) return '방금전';
    if (betweenTime < 60) {
        return `${betweenTime}분전`;
    }

    const betweenTimeHour = Math.floor(betweenTime / 60);
    if (betweenTimeHour < 24) {
        return `${betweenTimeHour}시간전`;
    }

    const betweenTimeDay = Math.floor(betweenTime / 60 / 24);
    if (betweenTimeDay < 365) {
        return `${betweenTimeDay}일전`;
    }

    return `${Math.floor(betweenTimeDay / 365)}년전`;
}
</script>

<div style="height:10rem;"></div>

<script src="{% static 'accounts/js/.js' %}"></script>

{% endblock content %}